# Generated by Django 3.1.7 on 2021-06-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroCrianca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contato')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('data_nascimento', models.CharField(max_length=50, verbose_name='Data Nascimento')),
                ('mae', models.CharField(max_length=100, verbose_name='Mãe')),
                ('pai', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pai')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(blank=True, choices=[('0', ''), ('man', 'homem'), ('woman', 'mulher')], max_length=5, null=True, verbose_name='gênero')),
            ],
            options={
                'verbose_name': 'child',
                'verbose_name_plural': 'childs',
                'ordering': ('name',),
            },
        ),
    ]
