# Generated by Django 3.1.7 on 2021-07-08 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadcrianca', '0003_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
