# Generated by Django 3.1.7 on 2021-07-12 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadcrianca', '0004_auto_20210708_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrocrianca',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cadastrocrianca',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
