# Generated by Django 3.1.7 on 2021-07-12 23:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadcrianca', '0005_auto_20210712_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrocrianca',
            name='user',
        ),
        migrations.AddField(
            model_name='cadastrocrianca',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
