# Generated by Django 3.1.7 on 2021-07-13 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadcrianca', '0006_auto_20210712_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrocrianca',
            name='user',
        ),
        migrations.AddField(
            model_name='cadastrocrianca',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
