# Generated by Django 3.1.7 on 2021-07-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadcrianca', '0007_auto_20210713_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(max_length=14, null=True, verbose_name='Cpf'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='name_completo',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(max_length=16, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.CharField(max_length=20),
        ),
    ]
