# Generated by Django 3.1.7 on 2021-07-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadcrianca', '0009_auto_20210716_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='user'),
        ),
    ]
